### ISSUE TITLE
index list and program list fail

### ISSUE THREAD

**Issue by miriam-e** [vadmium/python-iview#19]
iview-cli --index
fails with error message:

   Timeout accessing 'http://iview.abc.net.au/api/legacy/flash/?seriesIndex'

   iview-cli --programme
hangs for a long time before finally printing this error message:
	
	Traceback (most recent call last):
	  File "/usr/local/bin/iview-cli", line 303, in <module>
	    main()
	  File "/usr/local/bin/iview-cli", line 279, in main
	    programme()
	  File "/usr/local/bin/iview-cli", line 34, in programme
	    return category('index')
	  File "/usr/local/bin/iview-cli", line 38, in category
	    index = iview.comm.get_keyword(keyword)
	  File "/usr/local/lib/python3.3/site-packages/iview/comm.py", line 143, in get_keyword
	    return series_api('keyword', keyword)
	  File "/usr/local/lib/python3.3/site-packages/iview/comm.py", line 151, in series_api
	    index_data = maybe_fetch(url, (type,), headers=(authorization,))
	  File "/usr/local/lib/python3.3/site-packages/iview/comm.py", line 48, in maybe_fetch
	    return fetch_url(url, type, headers=headers)
	  File "/usr/local/lib/python3.3/site-packages/iview/comm.py", line 34, in fetch_url
	    return gzip.GzipFile(fileobj=http).read()
	  File "/usr/local/lib/python3.3/gzip.py", line 360, in read
	    self._read(readsize)
	  File "/usr/local/lib/python3.3/gzip.py", line 446, in _read
	    buf = self.fileobj.read(size)
	  File "/usr/local/lib/python3.3/gzip.py", line 84, in read
	    return self.file.read(size)
	  File "/usr/local/lib/python3.3/http/client.py", line 503, in read
	    return super(HTTPResponse, self).read(amt)
	  File "/usr/local/lib/python3.3/http/client.py", line 532, in readinto
	    return self._readinto_chunked(b)
	  File "/usr/local/lib/python3.3/http/client.py", line 634, in _readinto_chunked
	    n = self._safe_readinto(temp_mvb)
	  File "/usr/local/lib/python3.3/http/client.py", line 681, in _safe_readinto
	    n = self.fp.readinto(mvb)
	  File "/usr/local/lib/python3.3/socket.py", line 297, in readinto
	    return self._sock.recv_into(b)
	  File "/usr/local/lib/python3.3/ssl.py", line 453, in recv_into
	    return self.read(nbytes, buffer)
	  File "/usr/local/lib/python3.3/ssl.py", line 327, in read
	    v = self._sslobj.read(len, buffer)
	ConnectionResetError: [Errno 104] Connection reset by peer

The second problem (iview-cli --programme) might be caused by my very slow internet. I live in country Queensland, so have slow net access, and have no TV reception, which is why your sweet program is so useful to me. However I kind of doubt it. And I think the first problem (iview-cli --index) is almost certainly a problem with iview itself.

Anybody else having the same difficulties?

**Comment by iviewadmirer** [comment]
I've seen the same problem fetching the program.  It doesn't happen all the time, just "now and then", in exactly the same way you have reported it.

**Comment by vadmium** [comment]
Hello, I’ve been away. When I try the index now, it seems to work fine. Perhaps it was a temporary fault. I did have the idea to add an option for selecting different API backends, which might help work around when one of them stops working like this, but it would need more work.

Also, the --programme option downloads a largish JSON file of everything <https://feedtest:abc123@tviview.abc.net.au/iview/feed/Humax/?keyword=index>, currently 376 kB compressed. Perhaps the server that it comes from doesn’t like slow downloaders. It is a different server from the ones that serve the actual videos.

**Comment by miriam-e** [comment]
Sorry, I should have replied earlier. Yes. I'm able to download using the --programme option if I do so after midnight when my internet speed goes up a bit, so it seems you're right that it doesn't like slow connections.

And thank you for all the effort put into this program. I wouldn't be able to see any ABC if it wasn't for this. Goodness knows how many people miss out on the ABC because of lack of reception and slow internet. The ABC's charter requires that they be able to reach everybody in Australia, but it seems to have been conveniently overlooked in the midst of the damn DRM lunacy gripping much of the world today.

**Comment by gdurbrid** [comment]
miriam-e, to reduce slow downloads you could download the list of series and save it, since it doesn't change much, then search within each series with the series number which you can extract from the stored copy of the list. Something like this:
iview-cli -i > somefile # run this every week, or when a new series starts
iview-cli -s 4201219 # quick search for available episodes of George Gently

**Comment by miriam-e** [comment]
Thanks. Yep, I often do that. These days I do any iview listing and 
downloads after midnight, when speeds go up to turtle speed instead 
daytime's snail speed. :) Thank goodness for python-iview or I'd never 
get to see anything on ABC.


On 26/07/15 10:30, gdurbrid wrote:
> miriam-e, to reduce slow downloads you could download the list of series
> and save it, since it doesn't change much, then search within each
> series with the series number which you can extract from the stored copy
> of the list. Something like this:
> iview-cli -i > somefile # run this every week, or when a new series starts
> iview-cli -s 4201219 # quick search for available episodes of George Gently
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vadmium/python-iview/issues/19#issuecomment-124920994>.
>

-- 
If you don't have any failures then you're not trying hard enough.
  - Dr. Charles Elachi, director of NASA's Jet Propulsion Laboratory
-----
Website: http://miriam-english.org
Blogs:   http://miriam-e.dreamwidth.org
          http://miriam-e.livejournal.com

**Comment by vadmium** [comment]
Unfortunately with my change today, the --index option effectively downloads the same data as --programme now. I did raise the timeout to 30 s, though it sounds like that won’t help you.

One option might be try checkout the “redesign” branch. I think only the --index, --series, and --download work with that, and the series and episode codes are all different. But it uses a different web API with smaller downloads, so it might be more reliable for you.
