### ISSUE TITLE
debian package build fails on jessie

### ISSUE THREAD

**Issue by ajfclark** [vadmium/python-iview#22]
The `debian/rules binary` command fails, apparently due to a python version mismatch:

```
$ sudo ./debian/rules binary
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
test -x debian/rules
dh_testroot
dh_prep
dh_installdirs -A
mkdir -p "."
mkdir -p debian/python-module-stampdir
cd . && \
        python setup.py build \
        --build-base="/home/aclark/src/python-iview/./build"
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    import iview.config
  File "/home/aclark/src/python-iview/iview/config.py", line 26, in <module>
    akamaihd_key = bytes.fromhex(
AttributeError: type object 'str' has no attribute 'fromhex'
/usr/share/cdbs/1/class/python-distutils.mk:110: recipe for target 'debian/python-module-stampdir/python-iview' failed
make: *** [debian/python-module-stampdir/python-iview] Error 1
```

OS release:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by vadmium** [comment]
By the error message, it looks like it is trying to use Python 2. Are you able to use Python 3 on Jessie (i.e. “python3” command rather than “python”)?

The Debian build stuff is more or less inherited from when Jeremy wrote it (and Python-Iview used Python 2 then). I wouldn’t know how to fix it, but if you can suggest any fixes or pull requests I am happy to merge them in.

**Comment by ajfclark** [comment]
I've figured out the changes required to the rules and control files to get the package to build cleanly. Easiest to submit a patch here or do I need to fork, make a pull request etc?

**Comment by vadmium** [comment]
Thanks, I pushed your changes and hopefully it’s all fixed now
